const INVOICE_LIST_REQUEST = "INVOICE_LIST_REQUEST";
const INVOICE_LIST_SUCCESS = "INVOICE_LIST_SUCCESS";
const INVOICE_LIST_FAILURE = "INVOICE_LIST_FAILURE";

const INVOICE_CREATE_REQUEST = "INVOICE_CREATE_REQUEST";
const INVOICE_CREATE_SUCCESS = "INVOICE_CREATE_SUCCESS";
const INVOICE_CREATE_FAILURE = "INVOICE_CREATE_FAILURE";

const INVOICE_EDIT_REQUEST = "INVOICE_EDIT_REQUEST";
const INVOICE_EDIT_SUCCESS = "INVOICE_EDIT_SUCCESS";
const INVOICE_EDIT_FAILURE = "INVOICE_EDIT_FAILURE";

const FILTER_DRAFT = "FILTER_DRAFT";
const FILTER_ALL = "FILTER_ALL";
const FILTER_PENDING = "FILTER_PENDING";
const FILTER_PAID = "FILTER_PAID";

export const invoiceTypes = {
  INVOICE_LIST_FAILURE,
  INVOICE_LIST_REQUEST,
  INVOICE_LIST_SUCCESS,
  INVOICE_CREATE_FAILURE,
  INVOICE_CREATE_REQUEST,
  INVOICE_CREATE_SUCCESS,
  INVOICE_EDIT_REQUEST,
  INVOICE_EDIT_SUCCESS,
  INVOICE_EDIT_FAILURE,
};

export const filterTypes = {
  FILTER_DRAFT,
  FILTER_ALL,
  FILTER_PENDING,
  FILTER_PAID,
};

